import type { DataFactory } from '@rdfjs/types';
export default function namespace(factory?: DataFactory): {
    aboutUrl: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#aboutUrl">;
    base: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#base">;
    boolean: import("@rdfjs/types").NamedNode<"http://www.w3.org/2001/XMLSchema#boolean">;
    column: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#column">;
    datatype: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#datatype">;
    date: import("@rdfjs/types").NamedNode<"http://www.w3.org/2001/XMLSchema#date">;
    time: import("@rdfjs/types").NamedNode<"http://www.w3.org/2001/XMLSchema#time">;
    dateTime: import("@rdfjs/types").NamedNode<"http://www.w3.org/2001/XMLSchema#dateTime">;
    dateTimeStamp: import("@rdfjs/types").NamedNode<"http://www.w3.org/2001/XMLSchema#dateTimeStamp">;
    default: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#default">;
    delimiter: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#delimiter">;
    describes: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#describes">;
    dialect: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#dialect">;
    format: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#format">;
    integer: import("@rdfjs/types").NamedNode<"http://www.w3.org/2001/XMLSchema#integer">;
    lang: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#lang">;
    lineTerminators: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#lineTerminators">;
    name: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#name">;
    null: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#null">;
    propertyUrl: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#propertyUrl">;
    quoteChar: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#quoteChar">;
    row: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#row">;
    rownum: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#rownum">;
    string: import("@rdfjs/types").NamedNode<"http://www.w3.org/2001/XMLSchema#string">;
    suppressOutput: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#suppressOutput">;
    table: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#table">;
    tableSchema: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#tableSchema">;
    title: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#title">;
    type: import("@rdfjs/types").NamedNode<"http://www.w3.org/1999/02/22-rdf-syntax-ns#type">;
    url: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#url">;
    valueUrl: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#valueUrl">;
    virtual: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#virtual">;
    Row: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#Row">;
    Table: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#Table">;
    TableGroup: import("@rdfjs/types").NamedNode<"http://www.w3.org/ns/csvw#TableGroup">;
};
export type NS = ReturnType<typeof namespace>;
